[variables]
NIXPACKS_NODE_VERSION = "24"

[phases.install]
cmds = ["npm_config_production=false pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter @tennisillo/db build", "pnpm --filter @tennisillo/api build"]

[start]
cmd = "node apps/api/dist/main.js"
